---
- name: Creates directory
  file:
    path: /media/{{ loop_item | lower }}
    state: directory
    mode: 0777
  
- name: Mount up device by label
  mount:
    path: /media/{{ loop_item | lower }}
    src: "LABEL={{ loop_item }}"
    boot: False
    opts: "user,nofail,{{ device_type.option }}"
    fstype: "{{ device_type.value }}"
    state: present
  ignore_errors: True

- name: "get devices name"
  shell:
     cmd: "lsblk -o label,name,PARTTYPE -r | grep {{ loop_item }} | cut -d ' ' -f2  | sed '/^$/d' "
  register: result_1

- name: "Set fsck on boot  {{ result_1}}"
  cron:
    name: "sudo ./fsck.fat -V /dev/{{ device_item }}"
    special_time: reboot
    job: "sudo ./fsck.fat -V /dev/{{ device_item }} >/dev/null 2>&1"
  with_items: "{{ result_1.stdout_lines }}"
  loop_control:
    loop_var: device_item

- name: "Set fsck on boot  {{ result_1}}"
  cron:
    name: "sudo dosfsck -w -r -l -a -v -t /dev/{{ device_item }}"
    special_time: reboot
    job: "sudo dosfsck -w -r -l -a -v -t /dev/{{ device_item }} >/dev/null 2>&1"
  with_items: "{{ result_1.stdout_lines }}"
  loop_control:
    loop_var: device_item


