---
- name: "install apt-get packages"
  apt: 
    name: [ "usbmount", "exfat-fuse", "exfat-utils", "ntfs-3g", "lsof" ]
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: "set mount flag 1"
  replace:
    path: /lib/systemd/system/systemd-udevd.service
    regexp: 'MountFlags=slave'
    replace: 'MountFlags=shared'

- name: "set mount flag 2"
  lineinfile:
    path: /lib/systemd/system/systemd-udevd.service
    line: 'MountFlags=shared'

- name: "mount all types"
  include_tasks: mount.yaml  
  with_item:
  - { code: "0x7", value: "exfat" }
  - { code: "0xc", value: "vfat" }
  loop_control:
    loop_var: device_type

- name: "usb devices"
  shell:
    cmd: "lsblk -o name,mountpoint,label,size,uuid"
  register: result

- name: "usb show devices"  
  debug:
    msg: "{{ result.stdout_lines }}"