---
- name: "install apt-get packages"
  apt: 
    name: [ "usbmount", "exfat-fuse", "exfat-utils", "ntfs-3g", "lsof" ]
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: "set mount flag 1"
  replace:
    path: /lib/systemd/system/systemd-udevd.service
    regexp: 'MountFlags=slave'
    replace: 'MountFlags=shared'

- name: "set mount flag 2"
  lineinfile:
    path: /lib/systemd/system/systemd-udevd.service
    line: 'MountFlags=shared'

- name: "get devices"
  shell:
     cmd: "lsblk -o label,name | grep sd | cut -d ' ' -f1 | sed '/^$/d'"
  register: result

- name: Creates directory
  file:
    path: /media/{{ item | lower }}
    state: directory
  with_items: "{{ result.stdout_lines }}"

- name: Mount up device by label
  mount:
    path: /media/{{ item | lower }}
    src: "LABEL={{ item }}"
    boot: False
    opts: "user,nofail"
#    fstype: exfat
    state: present
  with_items: "{{ result.stdout_lines }}"
  ignore_errors: True

- name: "usb devices"
  shell:
    cmd: "lsblk -o name,mountpoint,label,size,uuid"
  register: result

- name: "usb show devices"  
  debug:
    msg: "{{ result.stdout_lines }}"