- name: Creates directory
  file:
    path: /media/{{ item }}
    state: directory
  with_items: "{{ labels }}"

- name: Mount up device by label
  mount:
    path: /media/{{ item }}
    src: "LABEL={{ item }}"
    fstype: exfat
    state: mounted
  with_items: "{{ labels }}"
  ignore_errors: True
