---
- name: "get devices {{ device_type.code }}"
  shell:
     cmd: "lsblk -o label,name,PARTTYPE | grep '{{ device_type.code }}' | grep sd | cut -d ' ' -f1 | sed '/^$/d'"
  register: result

- name: "mount all types"
  include_tasks: drive.yaml  
  with_items: "{{ result.stdout_lines }}"
  loop_control:
    loop_var: loop_item
