---
- name: hostapd install
  apt: name=hostapd state=present force=yes

- name: dnsmasq install
  apt: name=dnsmasq state=present force=yes

- name: dnsmasq.conf
  template:
    src: template/dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    backup: true

- name: hostapd.conf
  template:
    src: template/hostapd.conf.j2
    dest: /etc/hostapd/hostapd.conf
    backup: true

- name: hostapd
  template:
    src: template/hostapd.j2
    dest: /etc/default/hostapd
    backup: true

- name: rc.local
  template:
    src: template/rc.local.j2
    dest: /etc/rc.local
    backup: true

- name: interfaces
  template:
    src: template/interfaces.j2
    dest: /etc/network/interfaces
    backup: true

- name: networking service
  service: name=networking enabled=yes state=restarted

- name: dnsmasq service
  service: name=dnsmasq enabled=yes state=started

- name: Start hostapd service unmask
  shell:
    cmd: "systemctl unmask hostapd"

- name: Start hostapd service enable
  shell:
    cmd: "systemctl enable hostapd"

- name: Start hostapd service restart
  shell:
    cmd: "systemctl restart hostapd"

- name: Start hostapd service and enable on boot
  service:
    name: hostapd
    state: started
    enabled: yes
  notify: reboot
