#!/usr/bin/env ansible-playbook -i hosts --become -c paramiko
---
- name: Ansible Playbook for configuring aircrack on Raspberry Pi
  hosts: localhost
#  remote_user: pi
  become_user: root
  become: yes
  roles:
  - general
  - aircrack
