#!/usr/bin/env ansible-playbook -i hosts --become -c paramiko
---
- name: Ansible Playbook for change password on Raspberry Pi
  hosts: localhost
  become_user: root
  become: yes
  roles:
  - changepassword
  
