#!/usr/bin/env ansible-playbook -i hosts --become -c paramiko
---
- name: Ansible Playbook for configuring jukebox on Raspberry Pi
  hosts: localhost
#  remote_user: pi
  become_user: root
  become: yes
  roles:
  - general
  - usbdrive
#  - python
  - mopidy
  - nginx
  - hotspot
  - minidlna
  - ntp
  - music
  - zram
  - hifiberry
#  - { role: nodered,
#      become_user: pi }
  
