---
- name: "install apt-get packages"
  apt: 
    name: [ "curl" ]
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: "install remove libreoffice"
  apt:
    name: [ "libreoffice" ]
    state: absent

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: expand-rootfs
  shell:
    cmd: "raspi-config --expand-rootfs"
  notify: reboot    

- debug: msg="the value of foo.txt is {{lookup('file', 'pswrdfile') }}"

- name: Set a new password for the default "pi" account
  become: yes
  user:
    name: "pi"
    password: "{{ pi_password }}"