---
- name: "remove reroute all trafic to 192.168.1.1"
  lineinfile: 
    path: /etc/dnsmasq.conf    
    line: 'address=/#/192.168.1.1'
    state: absent

- name: Start dnsmasq service and enable on boot
  service:
    name: dnsmasq
    state: reloaded
    enabled: yes

- name: "install apt-get packages"
  apt: 
    name: [ "curl" ]
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: "install remove libreoffice"
  apt:
    name: [ "libreoffice" ]
    state: absent

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

#- name: expand-rootfs
#  shell:
#    cmd: "raspi-config --expand-rootfs"
#  notify: reboot    
