---
- name: "rpi-update"
  shell:
    cmd: rpi-update

- name: "remove reroute all trafic to 192.168.50.1"
  lineinfile: 
    path: /etc/dnsmasq.conf    
    line: 'address=/#/192.168.50.1'
    state: absent
  ignore_errors: true

- name: Start dnsmasq service and enable on boot
  service:
    name: dnsmasq
    state: reloaded
    enabled: yes
  ignore_errors: true
  
- name: upgrade
  apt: upgrade=yes
  become: true
  
- name: "install apt-get packages"
  apt: 
    name: [ "curl" ]
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: "install remove libreoffice"
  apt:
    name: [ "libreoffice" ]
    state: absent

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

#- name: expand-rootfs
#  shell:
#    cmd: "raspi-config --expand-rootfs"
#  notify: reboot    
