---
- name: Update APT package cache
  apt: update_cache=yes
  become: yes

- name: Update packages
  apt: upgrade=dist
  become: yes

- name: Install build packages
  apt:
      state: present
      name:
          - python3
          - python-pip
  become: yes
