---

# 0 means auto, and is the default
# 1 means analog
# 2 means HDMI
- name: Alsa sound connector
  lineinfile:
    regexp: amixer cset numid=3 ?
    line: amixer cset numid=3 {{ alsa_sound_connector }}
    insertbefore: '^exit 0$'
    dest: /etc/rc.local
  notify: play wav sound

- name: "copy asound.conf"  
  template:
    src: templates/asound.conf.j2
    dest: /etc/asound.conf
    mode: '0775'

- name: alsasink
  ini_file:
    dest: "{{ mopidy_conf_path }}"
    section: audio
    option: output
    value: alsasink
    backup: yes

- name: HDMI not DVI
  lineinfile:
    dest: /boot/config.txt
    line: hdmi_drive=2

- name: download example.wav
  get_url:
    url: https://file-examples.com/wp-content/uploads/2017/11/file_example_WAV_1MG.wav
    validate_certs: no
    dest: /home/pi/example.wav
    mode: '0775'
    force: yes
  notify: play wav sound
