- name: Ensure build directory exists
  file:
      path: "{{ item }}"
      state: directory
      recurse: yes
  with_items:
    - '{{ mopidy_media_dir }}/playlist'
    - '{{ mopidy_media_dir }}/music'
    - '{{ mopidy_media_dir }}/movie'