---
- name: "install apt-get packages"
  apt: 
    name: [ "python", "python-pip", "python3-pip" ]
    state: present
    update_cache: yes
    cache_valid_time: 3600

- include: locations.yml
- include: avahi.yml
- include: python27.yml
- include: pip.yml
- include: ipv6.yml
- include: alsa.yml
- include: mopidy.yml
- include: soundcloud.yml
- include: mopidy_packages.yml
- include: playlist.yml

- name: "List all ports"
  shell: |
    netstat -lnt | grep LISTEN | awk '{ print ( $4 ) }' | awk 'BEGIN{FS=":"} { print $(NF) }' | sort -n | uniq
  register: result

- name: "debug"  
  debug:
    msg: "{{ result.stdout_lines }}"