---
- name: "install apt-get packages"
  apt: 
    name: [ "python", "python-pip", "python3-pip" ]
    state: present
    update_cache: yes
    cache_valid_time: 3600

- include: locations.yml
- include: avahi.yml
- include: python27.yml
- include: pip.yml
- include: ipv6.yml
- include: alsa.yml
- include: mopidy.yml
- include: soundcloud.yml
- include: mopidy_packages.yml
- include: playlist.yml