---

- name: Pip moped
  pip:
    name: Mopidy-Moped    
  notify: restart mopidy

- name: Enable moped
  ini_file:
    dest: "{{ mopidy_conf_path }}"
    section: moped
    option: enabled
    backup: yes
  notify: restart mopidy
