---
- name: playlist.sh
  template:
    src: templates/playlist.sh.j2
    dest: /var/tmp/playlist.sh
    mode: '0775'
    
- name: "Create playlist runs every 1 hours"
  cron:
    name: "Create playlist"
    minute: "0" 
    job: "sudo /var/tmp/playlist.sh >/dev/null 2>&1"