---
- name: Ensure /etc/raspap directory exists
  file:
    path: "/etc/raspap/hostapd"
    state: directory
    recurse: yes
  notify: reboot

- name: copy file
  shell:
    cmd: "mv /var/www/html/installers/*log.sh /etc/raspap/hostapd"

#- name: "systemctl stopped"
#  systemd:
#    name: systemd-networkd
#    state: stopped

- name: "copy config"
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: yes
  with_items:
    - {"src": "/var/www/html/config/default_hostapd", "dest": "/etc/default/hostapd"}
    - {"src": "/var/www/html/config/hostapd.conf", "dest": "/etc/hostapd/hostapd.conf" }
    - {"src": "/var/www/html/config/dnsmasq.conf", "dest": "/etc/dnsmasq.d/090_raspap.conf" }
    - {"src": "/var/www/html/config/dhcpcd.conf", "dest": "/etc/dhcpcd.conf" }
#    - {"src": "/var/www/html/config/raspap-bridge-br0.netdev", "dest": "/etc/systemd/network/raspap-bridge-br0.netdev" }
#    - {"src": "/var/www/html/config/raspap-br0-member-eth0.network", "dest": "/etc/systemd/network/raspap-br0-member-eth0.network" }
    - {"src": "/var/www/html/config/config.php", "dest": "/var/www/html/includes/config.php" }

- name: "systemctl start systemd-networkd"
  systemd:
    name: systemd-networkd
    state: started
    enabled: yes

- name: "copy files"
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {"src": "hostapd.info", dest: "/etc/hostapd/hostapd.conf" }
    - {"src": "hostapd", dest: "/etc/default/hostapd" }
