---
- name: Ensure /etc/raspap directory exists
  file:
    path: "/etc/raspap/hostapd"
    state: directory
    recurse: yes
  notify: reboot

- name: copy file
  shell:
    cmd: "mv /var/www/html/installers/*log.sh /etc/raspap/hostapd"

- name: "systemctl update"
  shell: |
    systemctl daemon-reload
    systemctl enable raspapd.service
    cp /var/www/html/config/default_hostapd /etc/default/hostapd
    cp /var/www/html/config/hostapd.conf /etc/hostapd/hostapd.conf
    cp /var/www/html/config/dnsmasq.conf /etc/dnsmasq.d/090_raspap.conf
    cp /var/www/html/config/dhcpcd.conf /etc/dhcpcd.conf
    cp /var/www/html/config/raspap-bridge-br0.netdev /etc/systemd/network/raspap-bridge-br0.netdev
    sudo systemctl stop systemd-networkd
    sudo systemctl disable systemd-networkd
    cp /var/www/html/config/raspap-br0-member-eth0.network /etc/systemd/network/raspap-br0-member-eth0.network
    cp /var/www/html/config/config.php /var/www/html/includes/config.php
    echo "net.ipv4.ip_forward=1" | sudo tee /etc/sysctl.d/90_raspap.conf > /dev/null
    sysctl -p /etc/sysctl.d/90_raspap.conf
    /etc/init.d/procps restart
    systemctl start systemd-networkd"
    systemctl unmask hostapd.service
    systemctl enable hostapd.service
 
- name: "copy hostapd.conf"
  copy:
    src: "hostapd.conf"
    dest: "/etc/hostapd/hostapd.conf"
