---
- name: "Installing RaspAP"
  shell:
    cmd: "wget -q https://git.io/voEUQ -O /tmp/raspap && bash /tmp/raspap -y"

- name: copy file
  copy:
    src: raspap.auth
    dest: /etc/raspap/raspap.auth
    owner: www-data
    group: www-data
  notify: reboot

- name: "copy files"
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {"src": "hostapd.conf", dest: "/etc/hostapd/hostapd.conf" }
