---
- name: check if /var/www/html/raspap.php file exists
  stat: 
    path: /var/www/html/raspap.php
  register: stat_result

- name: "Installing RaspAP"
  shell:
    cmd: "wget -q https://git.io/voEUQ -O /tmp/raspap && bash /tmp/raspap -y"
  when: stat_result.stat.exists == False

- name: copy file
  copy:
    src: raspap.auth
    dest: /etc/raspap/raspap.auth
    owner: www-data
    group: www-data
  notify: reboot

- name: "copy files"
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {"src": "hostapd.conf", dest: "/etc/hostapd/hostapd.conf" }
    - {"src": "dhcpcd.conf", dest: "/etc/dhcpcd.conf" }    

- name: replace line
  lineinfile: 
    path: /etc/lighttpd/lighttpd.conf
    regexp: '^(.*)server.port(.*)$' 
    line: 'server.port = 8080'
    backrefs: yes

- name: replace line
  lineinfile: 
    path: /etc/dnsmasq.conf    
    line: 'address=/#/192.168.2.1'
    
