---
- name: check if /var/www/html/raspap.php file exists
  stat: 
    path: /var/www/html/raspap.php
  register: stat_result

- name: "Installing RaspAP"
  shell:
    cmd: "wget -q https://git.io/voEUQ -O /tmp/raspap && bash /tmp/raspap -y"
  when: stat_result.stat.exists == False

- name: copy file
  copy:
    src: raspap.auth
    dest: /etc/raspap/raspap.auth
    owner: www-data
    group: www-data
  notify: reboot

- name: "copy files"
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {"src": "hostapd.conf", dest: "/etc/hostapd/hostapd.conf" }
    - {"src": "dhcpcd.conf", dest: "/etc/dhcpcd.conf" }    

- name: Start dhcpcd service and enable on boot
  shell:
    cmd: "service dhcpcd reload"

#- name: replace line
#  lineinfile: 
#    path: /etc/lighttpd/lighttpd.conf
#    regexp: '^server.port(.*)$' 
#    line: 'server.port = 8080'

- name: Start lighttpd service and enable on boot
  service:
    name: lighttpd
    state: started
    enabled: yes

#- name: "reroute all trafic to 192.168.50.1"
#  lineinfile: 
#    path: /etc/dnsmasq.conf    
#    line: 'address=/#/192.168.50.1'

- name: Start dnsmasq service and enable on boot
  service:
    name: dnsmasq
    state: reloaded
    enabled: yes

- name: "List all ports"
  shell: |
    netstat -lnt | grep LISTEN | awk '{ print ( $4 ) }' | awk 'BEGIN{FS=":"} { print $(NF) }' | sort -n | uniq
  register: result

- name: "debug"  
  debug:
    msg: "{{ result.stdout_lines }}"

#- name: Start hostapd service and enable on boot
#  service:
#    name: hostapd
#    state: started
#    enabled: yes
  