---
- name: Remove directory
  file:
    path: /var/www/html
    state: absent  

- name: Ensure /var/www/html directory exists
  file:
    path: "/var/www/html"
    state: directory
    recurse: yes

- name: Extract html.zip into /var/www/html
  unarchive:
    src: raspap-webgui.zip
    dest: /var/www/html/
    owner: www-data
    group: www-data
    mode: 600

- name: Ensure /etc/raspap directory exists
  file:
    path: "/etc/raspap"
    state: directory
    recurse: yes

- name: copy file
  file:
    src: /var/www/html/raspap.php
    dest: /etc/raspap/raspap.php
    remote_src: yes  
    owner: www-data
    group: www-data

- name: Remove old /var/www/html/raspap.php
  file: 
    path:  /var/www/html/raspap.php
    state: absent    