---
- name: Remove directory
  file:
    path: /var/www/html
    state: absent  

- name: Extract html.zip into /var/www/html
  unarchive:
    src: html.zip
    dest: /var/www/
    owner: root
    mode: 600