---
- name: Remove directory
  file:
    path: /var/www/html
    state: absent  

- name: Extract html.zip into /var/www/html
  unarchive:
    src: raspap-webgui.zip
    dest: /var/www/
    owner: www-data
    group: www-data

- name: copy file
  copy:
    src: /var/www/html/raspap.php
    dest: /etc/raspap/raspap.php
    remote_src: yes  
    owner: www-data
    group: www-data

- name: Remove old /var/www/html/raspap.php
  file: 
    path:  /var/www/html/raspap.php
    state: absent    