---
- name: Trust mopidy developer GPG key
  apt_key:
    url: https://apt.mopidy.com/mopidy.gpg
    state: present

- name: Download apt_mopidy_com.list
  get_url:
    url: https://apt.mopidy.com/mopidy.list
    dest: /etc/apt/sources.list.d/apt_mopidy_com.list
    mode: '0775'

#- name: Ensure mopidy repository is available
#  apt_repository:
#    repo: deb https://apt.mopidy.com/ buster main contrib non-free
#    state: present
#    update_cache: no
    
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 0
  changed_when: False

- name: Ensure mopidy is installed
  apt:
    name: mopidy
    state: present

- name: Install mopidy packages
  apt:
    name: "{{ mopidy_packages }}"
    state: present
  when: mopidy_packages is defined
  notify: restart mopidy

- name: Start services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items: "{{ mopidy_packages }}"
  when: mopidy_packages is defined

- name: Install mopidy packages
  shell:
    cmd: "/usr/local/bin/pip{{ PYTHONVERSION }} install --upgrade pip"    

- name: Install mopidy packages
  pip:
    executable: /usr/local/bin/pip{{ PYTHONVERSION }}
    name: "{{ item }}"
    state: present
  with_items: "{{ mopidy_pip_packages }}"  
  notify: restart mopidy

- name: Ansible delete apt_mopidy_com.list
  file:
    path: /etc/apt/sources.list.d/apt_mopidy_com.list
    state: absent

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 0
  changed_when: False