---

- name: Update apt cache
  apt: 
    update_cache: yes
    cache_valid_time: 3600
  changed_when: False

- name: Install packages
  apt:
    name:
      - apt-transport-https
      - autoconf
      - gcc
      - python-dev
      - python-pip
      - gstreamer1.0-libav
    state: present
  notify: restart mopidy
