---
- name: lighttpd-enable-mod fastcgi-php
  shell:
    cmd: "lighttpd-enable-mod fastcgi-php"
  ignore_errors: true

- name: Start lighttpd service and enable on boot
  service:
    name: lighttpd
    state: reloaded
    enabled: yes

- name: "systemctl enable nodered.service"
  systemd:
    name: lighttpd
    state: started
    enabled: yes    
  
- name: "Ensure /etc/sudoers contains lines"
  lineinfile:
    name: /etc/sudoers
    line: "{{ item }}"
    state: present
  with_items:
    - "www-data ALL=(ALL) NOPASSWD:/sbin/ifdown wlan0"
    - "www-data ALL=(ALL) NOPASSWD:/sbin/ifup wlan0"
    - "www-data ALL=(ALL) NOPASSWD:/bin/cat /etc/wpa_supplicant/wpa_supplicant.conf"
    - "www-data ALL=(ALL) NOPASSWD:/bin/cp /tmp/wifidata /etc/wpa_supplicant/wpa_supplicant.conf"
    - "www-data ALL=(ALL) NOPASSWD:/sbin/wpa_cli -i wlan0 scan_results"
    - "www-data ALL=(ALL) NOPASSWD:/sbin/wpa_cli -i wlan0 scan"
    - "www-data ALL=(ALL) NOPASSWD:/sbin/wpa_cli -i wlan0 reconfigure"
    - "www-data ALL=(ALL) NOPASSWD:/bin/cp /tmp/hostapddata /etc/hostapd/hostapd.conf"
    - "www-data ALL=(ALL) NOPASSWD:/etc/init.d/hostapd start"
    - "www-data ALL=(ALL) NOPASSWD:/etc/init.d/hostapd stop"
    - "www-data ALL=(ALL) NOPASSWD:/etc/init.d/dnsmasq start"
    - "www-data ALL=(ALL) NOPASSWD:/etc/init.d/dnsmasq stop"
    - "www-data ALL=(ALL) NOPASSWD:/bin/cp /tmp/dhcpddata /etc/dnsmasq.conf"
    - "www-data ALL=(ALL) NOPASSWD:/sbin/shutdown -h now"
    - "www-data ALL=(ALL) NOPASSWD:/sbin/reboot"
    - "www-data ALL=(ALL) NOPASSWD:/sbin/ip link set wlan0 down"
    - "www-data ALL=(ALL) NOPASSWD:/sbin/ip link set wlan0 up"
    - "www-data ALL=(ALL) NOPASSWD:/sbin/ip -s a f label wlan0"
    - "www-data ALL=(ALL) NOPASSWD:/bin/cp /etc/raspap/networking/dhcpcd.conf /etc/dhcpcd.conf"
    - "www-data ALL=(ALL) NOPASSWD:/etc/raspap/hostapd/enablelog.sh"
    - "www-data ALL=(ALL) NOPASSWD:/etc/raspap/hostapd/disablelog.sh"  

- name: Add the user 'pi' to group www-data
  shell:
    cmd: "usermod -a -G www-data pi"
    
- name: "rm /etc/raspap/networking/defaults"    
  file:
    path: "/etc/raspap/networking/defaults"
    state: absent

- name: "Defaults from Raspberry Pi configuration"
  lineinfile:
    name: /etc/raspap/networking/defaults
    line: "{{ item }}"
    state: present
    create: true
  with_items:
    - "hostname"
    - "clientid"
    - "persistent"
    - "option rapid_commit"
    - "option domain_name_servers, domain_name, domain_search, host_name"
    - "option classless_static_routes"
    - "option ntp_servers"
    - "require dhcp_server_identifier"
    - "slaac private"
    - "nohook lookup-hostname"
    
    - "#denyinterfaces eth0 wlan0 #BRIDGED"    
    - "# RaspAP br0 configuration"
    - "interface br0"
    - "# RaspAP wlan0 configuration"
    - "interface wlan0"
    - "static ip_address=192.168.5.1/24"
    - "static routers=192.168.5.1"
    - "static domain_name_server=8.8.8.8 8.8.4.4"    
    - "# RaspAP uap0 configuration"
    - "interface uap0"
    - "static ip_address=192.168.5.1/24"
    - "nohook wpa_supplicant"

- name: "copy lighttpd/configport.sh"
  copy:
    src: /var/www/html/installers/configport.sh
    dest: /etc/raspap/lighttpd/configport.sh
    owner: www-data
    group: www-data
    mode: '0750'

#- name: replace line
#  lineinfile: 
#    path: /etc/lighttpd/lighttpd.conf
#    regexp: '^(.*)server.port(.*)$' 
#    line: 'server.port = 8080'
#    backrefs: yes
